---
# tasks users file for mariadb

- name: mariadb users
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    host: "{{ item.host | default('localhost') }}"
    priv: "{{ item.priv }}"
    append_privs: "{{ item.append_privs | default('no') }}"
    state: "{{ item.state | default('present') }}"
    login_user: root
    login_password: "{{ mariadb_root_pass }}"
  no_log: true
  with_items: "{{ mariadb_users }}"
