---
# defaults dbs file for Postgresql

- name: postgresql databases
  become_user: postgres
  postgresql_db:
    name: "{{ item.name }}"
    encoding: "{{ item.encoding | default('UTF-8') }}"
    lc_collate: "{{ item.lc_collate | default('C.UTF-8') }}"
    lc_ctype: "{{ item.lc_ctype | default('C.UTF-8') }}"
    template: "{{ item.template | default('template0') }}"
    owner: "{{ item.owner | default('postgres') }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ postgresql_databases }}"
