---
# defaults main file for Docker

docker_url: 'https://download.docker.com/linux/{{ ansible_distribution | lower }}'

docker_channel: 'stable'

docker_config:
  storage-driver: 'overlay2'
  log-driver: 'json-file'
  log-opts:
    max-size: '10m'
    max-file: '3'
  live-restore: true
