---
# tasks config file for LXD

- name: add lxd configuration file
  template:
    src: input.yml.j2
    dest: /tmp/input.yml

- name: init lxd configuration
  shell: lxd init --preseed < /tmp/input.yml

- name: copy template for systemd-resolved integration
  template:
    src: lxd-dns.service.j2
    dest: /etc/systemd/system/lxd-dns-{{ lxd_net_bridge }}.service
    owner: root
    group: root
    mode: 0644
