---
# tasks containers file for LXD

- name: Create a hello-world container
  lxd_container:
    name: hello-world
    state: started
    source:
      type: image
      mode: pull
      server: https://cloud-images.ubuntu.com/releases
      protocol: simplestreams
      alias: jammy
    profiles: ["default"]
    config: {"security.nesting": "true", "security.syscalls.intercept.mknod": "true", "security.syscalls.intercept.setxattr": "true"}
    wait_for_ipv4_addresses: true
    timeout: 600
